# Sreen Setings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player 
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_SHOOT_SPEED = 600
PLAYER_SHOOT_COOLDOWN = 0.1
# Shot
SHOT_RADIUS = 4


# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 5
ASTEROID_SPAWN_RATE = 0.25  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS