# Sreen Setings
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player 
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_SHOOT_SPEED = 600
PLAYER_SHOOT_COOLDOWN = 0.25

# Shot
SHOT_RADIUS = 5


# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.25  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Explosion 

EXPLOSION_MAX_SIZE = 8
EXPLOSION_MIN_SIZE = 4
EXPLOSION_DECAY = 0.1
EXPLOSION_LIFE_TIME = 1
